language: cpp
sudo: required

compiler:
    - gcc

before_script:
    - sudo apt-get install glew-utils 
    - sudo apt-get install libglew-dev 
    - mkdir build
    - cd build
    - cmake ..

script: make